### ISSUE TITLE
Error in R version  3.6.2 for abhy/sentiment

### ISSUE THREAD

**Issue by erivandosena** [abhy/sentiment#1]
Hi!

it seems that the install_github package installation devtools::install_github("abhy/sentiment") is not configured for the latest version of R 3.6.2

I am receiving the error message:
> devtools::install_github("abhy/sentiment")
Downloading GitHub repo abhy/sentiment@master
Skipping 1 packages not available: Rstem
   Error in file(filename, "r", encoding = encoding) : 
     não é possível abrir a conexão
   Calls: source -> file
   Além disso: Warning message:
   In file(filename, "r", encoding = encoding) :
     não foi possível abrir o arquivo 'packrat/init.R': No such file or directory
   Execução interrompida
Erro: Failed to install 'sentiment' from GitHub:
  System command error, exit status: 1, stdout + stderr:
E> Error in file(filename, "r", encoding = encoding) : 
E>   não é possível abrir a conexão
E> Calls: source -> file
E> Além disso: Warning message:
E> In file(filename, "r", encoding = encoding) :
E>   não foi possível abrir o arquivo 'packrat/init.R': No such file or directory
E> Execução interrompida

Any solution?

**Comment by abhy** [comment]
@erivandosena Unfortunately, the sentiment package is no longer supported. However, there are several alternative packages that you could use - [CRAN Task View: Natural Language Processing](https://cran.r-project.org/web/views/NaturalLanguageProcessing.html).

Here are two nice tutorials to get you started:
1. [Sentiment analysis with tidy data](https://www.tidytextmining.com/sentiment.html)
2. [Tidy Sentiment Analysis in R](https://www.datacamp.com/community/tutorials/sentiment-analysis-R)

**Comment by erivandosena** [comment]
Thank!

At.te,

*Erivando Sena*
Graduado em Análise e Desenvolvimento de Sistemas


*Bacharelando em Estatística (2019.2)Especializando MBA em Ciência de Dados
e Big Data Analytics (2019.1)Mestrando em Sociobiodiversidade e Tecnologias
Sustentáveis - Masts/Unilab (2018.2)*
http://lattes.cnpq.br/3207935358521360
www.erivandosena.com.br | facebook.com/erivandosenar |
twitter.com/erivandosena

"O verdadeiro sentido da vida não está na partida nem na chegada e sim na
trajetória."




Em sex., 3 de jan. de 2020 às 12:47, Abhay Sharma <notifications@github.com>
escreveu:
